import Swpr from "@/components/home/swpr/Swpr";
import Head from "next/head";
import { Fragment } from "react";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Horizontal Architect Agency</title>

        <link rel="icon" href="/icon.svg" />

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="application-name" content="Next.js" />
        <meta name="author" content="Maela" />
        <link rel="author" href="https://maelacudini.com" />
        <meta name="generator" content="Next.js" />
        <meta name="keywords" content="Next.js,React,JavaScript" />
        <meta name="referrer" content="origin-when-cross-origin" />
        <meta name="color-scheme" content="light" />
        <meta name="creator" content="Maela" />
        <meta name="publisher" content="Maela" />
        <meta name="format-detection" content="telephone=no, address=no, email=no" />
        <link rel="canonical" href="https://addwebsite.com" />
        <link rel="alternate" hrefLang="en-US" href="https://addwebsite.com/en-US" />

        <meta property="og:title" content="Horizontal Architect Agency" />
        <meta property="og:description" content="The React Framework for the Web" />
        <meta property="og:url" content="https://addwebsite.org/" />
        <meta property="og:site_name" content="Next.js" />
        <meta property="og:locale" content="en_US" />
        <meta property="og:image:url" content="https://addwebsite.org/card.png" />
        <meta property="og:image:width" content="800" />
        <meta property="og:image:height" content="600" />
        <meta property="og:image:alt" content="Horizontal Architecture Agency" />
        <meta property="og:type" content="website" />

        <meta name="robots" content="noindex, nofollow, nocache" />
        <meta
          name="googlebot"
          content="noindex, nofollow, noimageindex, max-video-preview:-1, max-image-preview:large, max-snippet:-1"
        />

        <link rel="shortcut icon" href="/icon.svg" />
        <link rel="icon" href="/icon.svg" />
        <link rel="apple-touch-icon" href="/icon.svg" />
        <link
          rel="apple-touch-icon-precomposed"
          href="/icon.svg"
        />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site:id" content="00000000000" />
        <meta name="twitter:creator" content="@no-one" />
        <meta name="twitter:creator:id" content="00000000000" />
        <meta name="twitter:title" content="Horizontal Architect Agency" />
        <meta name="twitter:description" content="The React Framework for the Web" />
        <meta name="twitter:image" content="https://addwebsite.org/card.png" />

        <meta name="theme-color" content="white" />
      </Head>
      <Swpr />
    </Fragment>
  );
}
